AdministrationModule_Group15/Controllers/ComponentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AdministrationModule.Domain.Entities;
using AdministrationModule.Domain.Repositories;
using AdministrationModule.Domain.Repositories.Component;
using AdministrationModule_Group15.Models;

namespace AdministrationModule_Group15.Controllers
{
    public class ComponentController : Controller
    {
        private readonly AbstractComponentRepo<Component> _componentRepository;
        private readonly IBaseRepository<Category> _categoryRepository;
        public ComponentController(AbstractComponentRepo<Component> componentRepository, IBaseRepository<Category> categoryRepository)
        {
            this._componentRepository = componentRepository;
            this._categoryRepository = categoryRepository;
        }


       //Get
        [HttpGet]
        public ViewResult Edit(int id)
        {
            Component componentToEdit = _componentRepository.FindById(id);

            return View(componentToEdit);
        }

        //Post
        [HttpPost]
        public ActionResult Edit(Component editedComponent)
        {
            if (ModelState.IsValid)
            {
                _componentRepository.Save(editedComponent);
                return RedirectToAction("Index", "Home");

            }
            else
            {
                return View(editedComponent);
            }

        }


        public ActionResult Delete(int id, int numberOfNumbersAndComments)
        {

            if (numberOfNumbersAndComments > 1)
            {
                _componentRepository.DeleteComponentAndComment(id);
                return RedirectToAction("Index", "Home");
            }

            _componentRepository.Delete(id);
            return RedirectToAction("Index", "Home");
        }

        [HttpGet]
        public ActionResult Create()
        {
            // Put the list of categories on the ViewBag!
            PutAllCategoriesOnViewBag();

            return View(new ComponentViewModel());
        }

        [HttpPost]
        public ActionResult Create(ComponentViewModel vm, HttpPostedFileBase file)
        {
            if (ModelState.IsValid)
            {
                Component componentToSave = new Component(); // the component to save in db
                ComponentNumberAndComment componentNumberAndComment = new ComponentNumberAndComment(); // the object specifying series# and component# for the component

                if (file != null)
                {
                    componentToSave.ImageMimeType = file.ContentType;
                    componentToSave.Image = new byte[file.ContentLength];
                    file.InputStream.Read(componentToSave.Image, 0, file.ContentLength);
                }

                //Set data in the component that should be saved
                componentToSave.ComponentInfo = vm.ComponentInfo;
                componentToSave.DataSheetUrl = vm.DataSheetUrl;
                componentToSave.ComponentName = vm.ComponentName;
                componentToSave.ManufactureLink = vm.ManufactureLink;

                //Create the componentnumberandcomment object for this component
                componentNumberAndComment.SeriesNr = vm.SeriesNr;
                componentNumberAndComment.ComponentNumberId = vm.ComponentNumberId;
                componentToSave.ComponentNumbers.Add(componentNumberAndComment);
                

                //Find the right category for the component
                var category = _categoryRepository.FindById(vm.CategoryId);
                if (category.Components == null)
                    category.Components = new List<Component>();

                //Add the component to this category!
                category.Components.Add(componentToSave);
                _categoryRepository.Save(category);


                return RedirectToAction("Index", "Home");
            }

            // Before going back, remember to put the categories in ViewBag!
            PutAllCategoriesOnViewBag();

            return View(vm);
        }


        [HttpGet]
        public PartialViewResult AddOneMoreComponent(int id)
        {
            return PartialView("Partials/AddOneMore", new ComponentNumberViewModel {Componentid = id});
        }

        [HttpPost]
        public ActionResult AddOneMoreComponent(ComponentNumberViewModel vm)
        {
            if (ModelState.IsValid)
            {

                _componentRepository.SaveComponentNumberAndComment(new ComponentNumberAndComment {SeriesNr = vm.SeriesNr, ComponentNumberId = vm.ComponentNumber}, vm.Componentid );
                return RedirectToAction("Index", "Home");
            }

            return PartialView("Partials/AddOneMore");
        }


        [HttpGet]
        public ViewResult ComponentDetails(int id)
        {
            return View(_componentRepository.FindById(id));
        }


        [HttpGet]
        public PartialViewResult ComponentNumberDetails(int id, string seriesNumber)
        {
            ComponentNumberAndComment componentNumberAndComment = _componentRepository.FindById(id).ComponentNumbers.First(cn => cn.SeriesNr == seriesNumber);
            return PartialView("Partials/ComponentDetailModal", componentNumberAndComment);
        }

        [HttpPost]
        public ActionResult ComponentNumberDetails(ComponentNumberAndComment model)
        {
            Component component = _componentRepository.FindById(model.ComponentId);

            if (!String.IsNullOrEmpty(model.UserComment) || !String.IsNullOrEmpty(model.AdminComment))
            {
                if (component != null)
                {
                    _componentRepository.SaveComponentNumberAndComment(model, component.ComponentId);
                }
            }
            return View("ComponentDetails", component);
        }




        #region Helpers

        private void PutAllCategoriesOnViewBag()
        {

            // First get all the existing categories
            IEnumerable<Category> categoriesList = _categoryRepository.GetAll();

            // Now add these to the Viewbag as a list of SelectListItems
            ViewBag.categories = categoriesList.Select(x =>
            new SelectListItem()
            {
                Text = x.CategoryName,
                Value = x.CategoryId.ToString()
            });
        }
        #endregion



    }
}

AdministrationModule_Group15/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AdministrationModule.Domain.Entities;
using AdministrationModule.Domain.Repositories;
using AdministrationModule.Domain.Repositories.Component;
using AdministrationModule_Group15.Models;

namespace AdministrationModule_Group15.Controllers
{
    [Authorize(Roles = "Admin")]
    public class HomeController : Controller
    {

        private AbstractComponentRepo<Component> _componentRepository;
        private IBaseRepository<Category> _categoryRepository;

        public HomeController(AbstractComponentRepo<Component> _componentRepository, IBaseRepository<Category> _categoryBaseRepository)
        {
            this._componentRepository = _componentRepository;
            this._categoryRepository = _categoryBaseRepository;
        }

        public ActionResult Index()
        {
            CategoriesAndComponents categoryComponent = new CategoriesAndComponents
            {
                Components = _componentRepository.GetAll().ToList(),
                Categories = _categoryRepository.GetAll().ToList()
            };

            return View(categoryComponent);
        }

        //Actionmethod for returning the home view with components only for a specific category
        public ViewResult ShowComponentsInCategory(int id )
        {

            CategoriesAndComponents categoryComponent = new CategoriesAndComponents();
            categoryComponent.Components = _componentRepository.GetAllFromCategory(id).ToList();
            categoryComponent.Categories = _categoryRepository.GetAll().ToList();

            ViewBag.Title = categoryComponent.Components[0].Category.CategoryName;

          
            return View("Index", categoryComponent);
        }


    }
}

AdministrationModule_Group15/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

AdministrationModule_Group15/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

AdministrationModule_Group15/Views/Home/Index.cshtml
@model AdministrationModule_Group15.Models.CategoriesAndComponents

@{
    ViewBag.Title = "Embedded Stock - Main Page";
}
@* Modal containers *@
<div class="modal fade in" id="addComponentModal">
    <div id="addComponent_container"></div>
</div>

<div class="modal fade in" id="addCategoryModal">
    <div id="addCategory_container"></div>
</div>
@* ********************************************** *@
<div class="row">
    @* Side nav bar *@
    <div class="col-md-4 navbar-left">
        @Html.Partial("Partials/Nav", Model.Categories)
    </div>

    <div class="col-xs-12 col-md-8">
        <div class="row btn-group">
            <div class="col-xs-12">
                <div class="btn btn-primary " id="addNewCategoryBtn">
                    Add category
                </div>
                @Html.ActionLink("Add component", "Create", "Component", null, new { @class = "btn btn-primary ", id = "addNewComponent" })
            </div>
            </div>
            <div class="row">
                <div class="col-md-12"></div>
                <table class="table table-bordered table-hover" id="componentTable">
                    <thead>
                        <tr>
                            <th>Image</th>
                            <th>Component</th>
                            <th class="visible-md">Category</th>
                            <th class="visible-md">Quantity</th>
                            <th>Options</th>
                        </tr>
                    </thead>

                    <tbody>
                        @foreach (var component in Model.Components)
                        {
                            <tr>
                                <td>
                                    @if (component.Image != null)
                                    {
                                        var base64 = Convert.ToBase64String(component.Image);
                                        var imgSrc = String.Format("data:image/gif;base64,{0}", base64);

                                        <img class="img-thumbnail" width="20%" src="@imgSrc" />
                                    }
                                </td>

                                <td>@Html.ActionLink(@component.ComponentName, "ComponentDetails", "Component", new { id = @component.ComponentId }, null)</td>
                                <td class="visible-md">@component.Category.CategoryName</td>
                                <td class="visible-md">@component.ComponentNumbers.Count()</td>
                                <td>
                                    <a class="addComponentModalBtn optionsButton" data-id="@component.ComponentId"><i class="fa fa-plus-circle"></i></a>  |
                                    <a href="@Url.Action("Edit", "Component", new { id = component.ComponentId })" class="optionsButton"><i class="fa fa-pencil">  </i></a>  |
                                    <a href="@Url.Action("Delete", "Component",
                                             new { id = component.ComponentId, numberOfNumbersAndComments = component.ComponentNumbers.Count() })"
                                       class="optionsButton"><i class="fa fa-trash"></i></a>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>

    </div>

    @*@section scripts{

            <script type="text/javascript" src="@Url.Content("~/Scripts/EmbeddedStock_Scripts/EmbStock.js")"></script>
        }*@